apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-deployment
spec:
  selector:
    matchLabels:
      app: banking-system
  replicas: 2 
  template:
    metadata:
      labels:
        app: banking-system
    spec:
      containers:
        - name: banking-system
          # Update this to your own Docker Hub username/repository name
          image: youngminds73/banking-system:latest 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8070 

---

apiVersion: v1
kind: Service
metadata:
  name: banking-service
spec:
  selector:
    app: banking-system
  ports:
    - protocol: "TCP"
      port: 8070 
      targetPort: 8070 
  type: LoadBalancer
